# Generated by Django 3.1.5 on 2021-01-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210128_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='latest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='top_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='top_sellers',
            field=models.BooleanField(default=False),
        ),
    ]
