# Generated by Django 3.1.5 on 2021-01-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_top_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='top_sellers',
        ),
    ]
