# Generated by Django 3.1.5 on 2021-02-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210201_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_product',
            field=models.ManyToManyField(blank=True, related_name='_product_related_product_+', to='store.Product'),
        ),
        migrations.DeleteModel(
            name='RelatedProduct',
        ),
    ]
