# Generated by Django 3.1.5 on 2021-02-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210201_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='related_product',
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='_product_related_products_+', to='store.Product'),
        ),
    ]
