# Generated by Django 3.1.5 on 2021-02-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210201_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
